//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdleMasterExtended.localization {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdleMasterExtended.localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Accept benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Add benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Game to Blacklist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string add_game_blacklist {
            get {
                return ResourceManager.GetString("add_game_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Game to Whitelist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string add_game_whitelist {
            get {
                return ResourceManager.GetString("add_game_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display advanced authentication information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string advanced_auth {
            get {
                return ResourceManager.GetString("advanced_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master Authentication Data benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string auth_data {
            get {
                return ResourceManager.GetString("auth_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Badge page didn&apos;t load, will retry in __num__ seconds benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string badge_didnt_load {
            get {
                return ResourceManager.GetString("badge_didnt_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Blacklist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Blacklist Current Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string blacklist_current_game {
            get {
                return ResourceManager.GetString("blacklist_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Cancel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   card drops remaining benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string card_drops_remaining {
            get {
                return ResourceManager.GetString("card_drops_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear All benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string clear_all {
            get {
                return ResourceManager.GetString("clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display information above
        ///
        ///[WARNING]
        ///Do not share this information with anyone,
        ///as it could potentially be used by an attacker to log into
        ///your Steam account. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string cookie_warning {
            get {
                return ResourceManager.GetString("cookie_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currently in-game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string currently_ingame {
            get {
                return ResourceManager.GetString("currently_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E&amp;xit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string export_blacklist {
            get {
                return ResourceManager.GetString("export_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string game {
            get {
                return ResourceManager.GetString("game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   games left to idle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string games_left_to_idle {
            get {
                return ResourceManager.GetString("games_left_to_idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hours benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   hrs on record benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hrs_on_record {
            get {
                return ResourceManager.GetString("hrs_on_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle each game individually benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_individual {
            get {
                return ResourceManager.GetString("idle_individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master is connected to Steam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_master_connected {
            get {
                return ResourceManager.GetString("idle_master_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master is not connected to Steam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_master_notconnected {
            get {
                return ResourceManager.GetString("idle_master_notconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_master_settings {
            get {
                return ResourceManager.GetString("idle_master_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   idle now benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_now {
            get {
                return ResourceManager.GetString("idle_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle games with more than 2 hours individually, then simultaneously benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_onethenmany {
            get {
                return ResourceManager.GetString("idle_onethenmany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle games simultaneously up to 2 hours, then individually benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idle_simultaneous {
            get {
                return ResourceManager.GetString("idle_simultaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idling Behavior benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idling_behavior {
            get {
                return ResourceManager.GetString("idling_behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idling complete, no more card drops available benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idling_complete {
            get {
                return ResourceManager.GetString("idling_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idling Order benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idling_order {
            get {
                return ResourceManager.GetString("idling_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idling paused benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string idling_paused {
            get {
                return ResourceManager.GetString("idling_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore Steam client status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ignore_client_status {
            get {
                return ResourceManager.GetString("ignore_client_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interface Language benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string interface_language {
            get {
                return ResourceManager.GetString("interface_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading next game... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string loading_next {
            get {
                return ResourceManager.GetString("loading_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Idle Master Blacklist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string manage_blacklist {
            get {
                return ResourceManager.GetString("manage_blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Idle Master Whitelist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string manage_whitelist {
            get {
                return ResourceManager.GetString("manage_whitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize Idle Master to system tray benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string minimize_to_tray {
            get {
                return ResourceManager.GetString("minimize_to_tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string msg_delete_all_head {
            get {
                return ResourceManager.GetString("msg_delete_all_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete all? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string msg_delete_all_text {
            get {
                return ResourceManager.GetString("msg_delete_all_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next check benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string next_check {
            get {
                return ResourceManager.GetString("next_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not in game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string not_ingame {
            get {
                return ResourceManager.GetString("not_ingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Official Group benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string official_group {
            get {
                return ResourceManager.GetString("official_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;OK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default (Alphabetical Order) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string order_default {
            get {
                return ResourceManager.GetString("order_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prioritize games with the lowest number of available drops benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string order_least {
            get {
                return ResourceManager.GetString("order_least", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prioritize games with the highest number of available drops benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string order_most {
            get {
                return ResourceManager.GetString("order_most", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prioritize games with the highest card values benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string order_value {
            get {
                return ResourceManager.GetString("order_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Pause Idling benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string pause_idling {
            get {
                return ResourceManager.GetString("pause_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Login to Steam benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string please_login {
            get {
                return ResourceManager.GetString("please_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart the application for language changes to take effect. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string please_restart {
            get {
                return ResourceManager.GetString("please_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   please wait... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading badge page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string reading_badge_page {
            get {
                return ResourceManager.GetString("reading_badge_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Release Notes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string release_notes {
            get {
                return ResourceManager.GetString("release_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master Release Notes benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string release_notes_title {
            get {
                return ResourceManager.GetString("release_notes_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Resume Idling benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string resume_idling {
            get {
                return ResourceManager.GetString("resume_idling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Save benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Idle Master is saving your information benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string saving_info {
            get {
                return ResourceManager.GetString("saving_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Settings benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Steam username of signed on user benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string show_username {
            get {
                return ResourceManager.GetString("show_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Signed in as benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string signed_in_as {
            get {
                return ResourceManager.GetString("signed_in_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Skip Current Game benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string skip_current_game {
            get {
                return ResourceManager.GetString("skip_current_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorting results based on your settings, please wait... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sorting_results {
            get {
                return ResourceManager.GetString("sorting_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Statistics benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steam client status ignored benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string steam_ignored {
            get {
                return ResourceManager.GetString("steam_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steam is not running benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string steam_notrunning {
            get {
                return ResourceManager.GetString("steam_notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Steam is running benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string steam_running {
            get {
                return ResourceManager.GetString("steam_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Session benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string this_session {
            get {
                return ResourceManager.GetString("this_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Total benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Update benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update games status benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string update_games_status {
            get {
                return ResourceManager.GetString("update_games_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data you&apos;ve entered isn&apos;t valid.  Please try again. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string validate_failed {
            get {
                return ResourceManager.GetString("validate_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Validating... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string validating {
            get {
                return ResourceManager.GetString("validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Whitelist benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string whitelist {
            get {
                return ResourceManager.GetString("whitelist", resourceCulture);
            }
        }
    }
}
